name: Build Static Site and Release to Public Repo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.1
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run build:rockets-ui
      - run: zip -r dist.zip dist
      - run: zip -r dist-rockets-ui.zip dist-rockets-ui
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_number }}
          repository: CSI-Rockets-Eletronics/ControlCenterUI-Release
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          files: |
            dist.zip
            dist-rockets-ui.zip
